### PR TITLE
[CI] move to github action

### PR DESCRIPTION
**Pull request by littleGnAl**

### CODE REVIEW

**Comment by littleGnAl** [comment]
Blocked https://github.com/littleGnAl/http_proxy_override/pull/5

**Comment by Vlad-Adrian** [comment]
The changes in the gradle files will probably create conflicts with my changes. Can you try using the same versions as mine?

**Comment by littleGnAl** [comment]
Sorry for making you inconvenient. Upgrading to a newer version of Gradle may cause other versioning changes, so I try to make a minimum change to let the CI happy first, I think you can safely accept your changes when conflicts arise.

**Comment by littleGnAl** [comment]
I will merge this first to allow the PR to be checked by the CI.

**Pull request merged**
